# Generated by Django 5.0.3 on 2024-03-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("private", "Private"),
                    ("public", "Public"),
                    ("professional", "Professional"),
                ],
                default="public",
                max_length=50,
            ),
        ),
    ]
