# Generated by Django 5.0.3 on 2024-03-07 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="posts/")),
                (
                    "caption",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "music",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "hide_like_and_view_counts",
                    models.BooleanField(default=False),
                ),
                ("turn_off_comments", models.BooleanField(default=False)),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("followers", "Followers"),
                            ("closed_friends", "Closed Friends"),
                        ],
                        default="followers",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
