# Generated by Django 5.0.3 on 2024-03-11 10:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_alter_post_audience"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="postlike",
            unique_together={("post", "liked_by")},
        ),
    ]
