# Generated by Django 5.0.3 on 2024-03-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_alter_postlike_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="postlike",
            name="is_liked",
            field=models.BooleanField(default=True),
        ),
    ]
